build:

  environment:
    mysql: false
    postgresql: false
    redis: false
    rabbitmq: false
    php:
      version: 7.1
    docker:
      cache:
        images:
          - "werkspot/message-bus:*"

  tests:
    override:
      -
        command: make test-with-coverage
        coverage:
          file: coverage.clover.xml
          format: php-clover

filter:
  paths:
    - "src/"
  dependency_paths:
    - "vendor/"

build_failure_conditions:
  - 'issues.new.exists'
  - 'project.metric("scrutinizer.test_coverage", < 1.0)'
